// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExpensesColumns holds the columns for the "expenses" table.
	ExpensesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString, Default: "ETB"},
		{Name: "category", Type: field.TypeString},
		{Name: "raw_input", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_expenses", Type: field.TypeUUID},
	}
	// ExpensesTable holds the schema information for the "expenses" table.
	ExpensesTable = &schema.Table{
		Name:       "expenses",
		Columns:    ExpensesColumns,
		PrimaryKey: []*schema.Column{ExpensesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "expenses_users_expenses",
				Columns:    []*schema.Column{ExpensesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "telegram_id", Type: field.TypeInt64, Unique: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "Africa/Addis_Ababa"},
		{Name: "currency", Type: field.TypeString, Default: "ETB"},
		{Name: "language", Type: field.TypeString, Default: "en"},
		{Name: "is_premium", Type: field.TypeBool, Default: false},
		{Name: "current_streak", Type: field.TypeInt, Default: 0},
		{Name: "referred_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExpensesTable,
		UsersTable,
	}
)

func init() {
	ExpensesTable.ForeignKeys[0].RefTable = UsersTable
}
