// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"INCOME", "EXPENSE"}, Default: "EXPENSE"},
		{Name: "currency", Type: field.TypeString, Default: "ETB"},
		{Name: "category", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "raw_input", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_transactions", Type: field.TypeUUID},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_users_transactions",
				Columns:    []*schema.Column{TransactionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "telegram_id", Type: field.TypeInt64, Unique: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "timezone", Type: field.TypeString, Default: "Africa/Addis_Ababa"},
		{Name: "currency", Type: field.TypeString, Default: "ETB"},
		{Name: "language", Type: field.TypeString, Default: "en"},
		{Name: "is_premium", Type: field.TypeBool, Default: false},
		{Name: "current_streak", Type: field.TypeInt, Default: 0},
		{Name: "referred_by", Type: field.TypeUUID, Nullable: true},
		{Name: "full_name", Type: field.TypeString, Nullable: true},
		{Name: "phone_number", Type: field.TypeString, Nullable: true},
		{Name: "onboarding_state", Type: field.TypeString, Default: "AWAITING_NAME"},
		{Name: "onboarding_completed", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	TransactionsTable.ForeignKeys[0].RefTable = UsersTable
}
