// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pocka/ent/budget"
	"pocka/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BudgetCreate is the builder for creating a Budget entity.
type BudgetCreate struct {
	config
	mutation *BudgetMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *BudgetCreate) SetAmount(v float64) *BudgetCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *BudgetCreate) SetCategory(v string) *BudgetCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *BudgetCreate) SetNillableCategory(v *string) *BudgetCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetPeriod sets the "period" field.
func (_c *BudgetCreate) SetPeriod(v string) *BudgetCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_c *BudgetCreate) SetNillablePeriod(v *string) *BudgetCreate {
	if v != nil {
		_c.SetPeriod(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BudgetCreate) SetCreatedAt(v time.Time) *BudgetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BudgetCreate) SetNillableCreatedAt(v *time.Time) *BudgetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BudgetCreate) SetID(v uuid.UUID) *BudgetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BudgetCreate) SetNillableID(v *uuid.UUID) *BudgetCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *BudgetCreate) SetUserID(id uuid.UUID) *BudgetCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BudgetCreate) SetUser(v *User) *BudgetCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (_c *BudgetCreate) Mutation() *BudgetMutation {
	return _c.mutation
}

// Save creates the Budget in the database.
func (_c *BudgetCreate) Save(ctx context.Context) (*Budget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BudgetCreate) SaveX(ctx context.Context) *Budget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BudgetCreate) defaults() {
	if _, ok := _c.mutation.Period(); !ok {
		v := budget.DefaultPeriod
		_c.mutation.SetPeriod(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := budget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := budget.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BudgetCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Budget.amount"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Budget.period"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Budget.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Budget.user"`)}
	}
	return nil
}

func (_c *BudgetCreate) sqlSave(ctx context.Context) (*Budget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BudgetCreate) createSpec() (*Budget, *sqlgraph.CreateSpec) {
	var (
		_node = &Budget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(budget.Table, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(budget.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(budget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_budgets = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BudgetCreateBulk is the builder for creating many Budget entities in bulk.
type BudgetCreateBulk struct {
	config
	err      error
	builders []*BudgetCreate
}

// Save creates the Budget entities in the database.
func (_c *BudgetCreateBulk) Save(ctx context.Context) ([]*Budget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Budget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BudgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BudgetCreateBulk) SaveX(ctx context.Context) []*Budget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
