// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pocka/ent/budget"
	"pocka/ent/predicate"
	"pocka/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BudgetUpdate is the builder for updating Budget entities.
type BudgetUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetMutation
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdate) Where(ps ...predicate.Budget) *BudgetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdate) SetAmount(v float64) *BudgetUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableAmount(v *float64) *BudgetUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdate) AddAmount(v float64) *BudgetUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCategory sets the "category" field.
func (_u *BudgetUpdate) SetCategory(v string) *BudgetUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillableCategory(v *string) *BudgetUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *BudgetUpdate) ClearCategory() *BudgetUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetUpdate) SetPeriod(v string) *BudgetUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetUpdate) SetNillablePeriod(v *string) *BudgetUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BudgetUpdate) SetUserID(id uuid.UUID) *BudgetUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BudgetUpdate) SetUser(v *User) *BudgetUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdate) Mutation() *BudgetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BudgetUpdate) ClearUser() *BudgetUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.user"`)
	}
	return nil
}

func (_u *BudgetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(budget.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(budget.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetUpdateOne is the builder for updating a single Budget entity.
type BudgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetMutation
}

// SetAmount sets the "amount" field.
func (_u *BudgetUpdateOne) SetAmount(v float64) *BudgetUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableAmount(v *float64) *BudgetUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BudgetUpdateOne) AddAmount(v float64) *BudgetUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCategory sets the "category" field.
func (_u *BudgetUpdateOne) SetCategory(v string) *BudgetUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillableCategory(v *string) *BudgetUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *BudgetUpdateOne) ClearCategory() *BudgetUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetUpdateOne) SetPeriod(v string) *BudgetUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetUpdateOne) SetNillablePeriod(v *string) *BudgetUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BudgetUpdateOne) SetUserID(id uuid.UUID) *BudgetUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BudgetUpdateOne) SetUser(v *User) *BudgetUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (_u *BudgetUpdateOne) Mutation() *BudgetMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BudgetUpdateOne) ClearUser() *BudgetUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the BudgetUpdate builder.
func (_u *BudgetUpdateOne) Where(ps ...predicate.Budget) *BudgetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetUpdateOne) Select(field string, fields ...string) *BudgetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Budget entity.
func (_u *BudgetUpdateOne) Save(ctx context.Context) (*Budget, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetUpdateOne) SaveX(ctx context.Context) *Budget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.user"`)
	}
	return nil
}

func (_u *BudgetUpdateOne) sqlSave(ctx context.Context) (_node *Budget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Budget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budget.FieldID)
		for _, f := range fields {
			if !budget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(budget.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(budget.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Budget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
