// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pocka/ent/schema"
	"pocka/ent/transaction"
	"pocka/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCurrency is the schema descriptor for currency field.
	transactionDescCurrency := transactionFields[3].Descriptor()
	// transaction.DefaultCurrency holds the default value on creation for the currency field.
	transaction.DefaultCurrency = transactionDescCurrency.Default.(string)
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionFields[9].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTimezone is the schema descriptor for timezone field.
	userDescTimezone := userFields[3].Descriptor()
	// user.DefaultTimezone holds the default value on creation for the timezone field.
	user.DefaultTimezone = userDescTimezone.Default.(string)
	// userDescCurrency is the schema descriptor for currency field.
	userDescCurrency := userFields[4].Descriptor()
	// user.DefaultCurrency holds the default value on creation for the currency field.
	user.DefaultCurrency = userDescCurrency.Default.(string)
	// userDescLanguage is the schema descriptor for language field.
	userDescLanguage := userFields[5].Descriptor()
	// user.DefaultLanguage holds the default value on creation for the language field.
	user.DefaultLanguage = userDescLanguage.Default.(string)
	// userDescIsPremium is the schema descriptor for is_premium field.
	userDescIsPremium := userFields[6].Descriptor()
	// user.DefaultIsPremium holds the default value on creation for the is_premium field.
	user.DefaultIsPremium = userDescIsPremium.Default.(bool)
	// userDescCurrentStreak is the schema descriptor for current_streak field.
	userDescCurrentStreak := userFields[7].Descriptor()
	// user.DefaultCurrentStreak holds the default value on creation for the current_streak field.
	user.DefaultCurrentStreak = userDescCurrentStreak.Default.(int)
	// userDescOnboardingState is the schema descriptor for onboarding_state field.
	userDescOnboardingState := userFields[11].Descriptor()
	// user.DefaultOnboardingState holds the default value on creation for the onboarding_state field.
	user.DefaultOnboardingState = userDescOnboardingState.Default.(string)
	// userDescOnboardingCompleted is the schema descriptor for onboarding_completed field.
	userDescOnboardingCompleted := userFields[12].Descriptor()
	// user.DefaultOnboardingCompleted holds the default value on creation for the onboarding_completed field.
	user.DefaultOnboardingCompleted = userDescOnboardingCompleted.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[14].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
