// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pocka/ent/expense"
	"pocka/ent/schema"
	"pocka/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	expenseFields := schema.Expense{}.Fields()
	_ = expenseFields
	// expenseDescCurrency is the schema descriptor for currency field.
	expenseDescCurrency := expenseFields[2].Descriptor()
	// expense.DefaultCurrency holds the default value on creation for the currency field.
	expense.DefaultCurrency = expenseDescCurrency.Default.(string)
	// expenseDescCreatedAt is the schema descriptor for created_at field.
	expenseDescCreatedAt := expenseFields[5].Descriptor()
	// expense.DefaultCreatedAt holds the default value on creation for the created_at field.
	expense.DefaultCreatedAt = expenseDescCreatedAt.Default.(func() time.Time)
	// expenseDescID is the schema descriptor for id field.
	expenseDescID := expenseFields[0].Descriptor()
	// expense.DefaultID holds the default value on creation for the id field.
	expense.DefaultID = expenseDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTimezone is the schema descriptor for timezone field.
	userDescTimezone := userFields[3].Descriptor()
	// user.DefaultTimezone holds the default value on creation for the timezone field.
	user.DefaultTimezone = userDescTimezone.Default.(string)
	// userDescCurrency is the schema descriptor for currency field.
	userDescCurrency := userFields[4].Descriptor()
	// user.DefaultCurrency holds the default value on creation for the currency field.
	user.DefaultCurrency = userDescCurrency.Default.(string)
	// userDescLanguage is the schema descriptor for language field.
	userDescLanguage := userFields[5].Descriptor()
	// user.DefaultLanguage holds the default value on creation for the language field.
	user.DefaultLanguage = userDescLanguage.Default.(string)
	// userDescIsPremium is the schema descriptor for is_premium field.
	userDescIsPremium := userFields[6].Descriptor()
	// user.DefaultIsPremium holds the default value on creation for the is_premium field.
	user.DefaultIsPremium = userDescIsPremium.Default.(bool)
	// userDescCurrentStreak is the schema descriptor for current_streak field.
	userDescCurrentStreak := userFields[7].Descriptor()
	// user.DefaultCurrentStreak holds the default value on creation for the current_streak field.
	user.DefaultCurrentStreak = userDescCurrentStreak.Default.(int)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[9].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
