// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pocka/ent/budget"
	"pocka/ent/transaction"
	"pocka/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetTelegramID sets the "telegram_id" field.
func (_c *UserCreate) SetTelegramID(v int64) *UserCreate {
	_c.mutation.SetTelegramID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsername(v *string) *UserCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *UserCreate) SetTimezone(v string) *UserCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *UserCreate) SetNillableTimezone(v *string) *UserCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *UserCreate) SetCurrency(v string) *UserCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *UserCreate) SetNillableCurrency(v *string) *UserCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *UserCreate) SetLanguage(v string) *UserCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *UserCreate) SetNillableLanguage(v *string) *UserCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetIsPremium sets the "is_premium" field.
func (_c *UserCreate) SetIsPremium(v bool) *UserCreate {
	_c.mutation.SetIsPremium(v)
	return _c
}

// SetNillableIsPremium sets the "is_premium" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsPremium(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsPremium(*v)
	}
	return _c
}

// SetCurrentStreak sets the "current_streak" field.
func (_c *UserCreate) SetCurrentStreak(v int) *UserCreate {
	_c.mutation.SetCurrentStreak(v)
	return _c
}

// SetNillableCurrentStreak sets the "current_streak" field if the given value is not nil.
func (_c *UserCreate) SetNillableCurrentStreak(v *int) *UserCreate {
	if v != nil {
		_c.SetCurrentStreak(*v)
	}
	return _c
}

// SetReferrerID sets the "referrer_id" field.
func (_c *UserCreate) SetReferrerID(v int64) *UserCreate {
	_c.mutation.SetReferrerID(v)
	return _c
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_c *UserCreate) SetNillableReferrerID(v *int64) *UserCreate {
	if v != nil {
		_c.SetReferrerID(*v)
	}
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *UserCreate) SetFullName(v string) *UserCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableFullName(v *string) *UserCreate {
	if v != nil {
		_c.SetFullName(*v)
	}
	return _c
}

// SetPhoneNumber sets the "phone_number" field.
func (_c *UserCreate) SetPhoneNumber(v string) *UserCreate {
	_c.mutation.SetPhoneNumber(v)
	return _c
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_c *UserCreate) SetNillablePhoneNumber(v *string) *UserCreate {
	if v != nil {
		_c.SetPhoneNumber(*v)
	}
	return _c
}

// SetOnboardingState sets the "onboarding_state" field.
func (_c *UserCreate) SetOnboardingState(v string) *UserCreate {
	_c.mutation.SetOnboardingState(v)
	return _c
}

// SetNillableOnboardingState sets the "onboarding_state" field if the given value is not nil.
func (_c *UserCreate) SetNillableOnboardingState(v *string) *UserCreate {
	if v != nil {
		_c.SetOnboardingState(*v)
	}
	return _c
}

// SetOnboardingCompleted sets the "onboarding_completed" field.
func (_c *UserCreate) SetOnboardingCompleted(v bool) *UserCreate {
	_c.mutation.SetOnboardingCompleted(v)
	return _c
}

// SetNillableOnboardingCompleted sets the "onboarding_completed" field if the given value is not nil.
func (_c *UserCreate) SetNillableOnboardingCompleted(v *bool) *UserCreate {
	if v != nil {
		_c.SetOnboardingCompleted(*v)
	}
	return _c
}

// SetLastLogDate sets the "last_log_date" field.
func (_c *UserCreate) SetLastLogDate(v time.Time) *UserCreate {
	_c.mutation.SetLastLogDate(v)
	return _c
}

// SetNillableLastLogDate sets the "last_log_date" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastLogDate(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetLastLogDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v uuid.UUID) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserCreate) SetNillableID(v *uuid.UUID) *UserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *UserCreate) AddTransactionIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *UserCreate) AddTransactions(v ...*Transaction) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (_c *UserCreate) AddBudgetIDs(ids ...uuid.UUID) *UserCreate {
	_c.mutation.AddBudgetIDs(ids...)
	return _c
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (_c *UserCreate) AddBudgets(v ...*Budget) *UserCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBudgetIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.Timezone(); !ok {
		v := user.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := user.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := user.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.IsPremium(); !ok {
		v := user.DefaultIsPremium
		_c.mutation.SetIsPremium(v)
	}
	if _, ok := _c.mutation.CurrentStreak(); !ok {
		v := user.DefaultCurrentStreak
		_c.mutation.SetCurrentStreak(v)
	}
	if _, ok := _c.mutation.OnboardingState(); !ok {
		v := user.DefaultOnboardingState
		_c.mutation.SetOnboardingState(v)
	}
	if _, ok := _c.mutation.OnboardingCompleted(); !ok {
		v := user.DefaultOnboardingCompleted
		_c.mutation.SetOnboardingCompleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := user.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.TelegramID(); !ok {
		return &ValidationError{Name: "telegram_id", err: errors.New(`ent: missing required field "User.telegram_id"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "User.timezone"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "User.currency"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "User.language"`)}
	}
	if _, ok := _c.mutation.IsPremium(); !ok {
		return &ValidationError{Name: "is_premium", err: errors.New(`ent: missing required field "User.is_premium"`)}
	}
	if _, ok := _c.mutation.CurrentStreak(); !ok {
		return &ValidationError{Name: "current_streak", err: errors.New(`ent: missing required field "User.current_streak"`)}
	}
	if _, ok := _c.mutation.OnboardingState(); !ok {
		return &ValidationError{Name: "onboarding_state", err: errors.New(`ent: missing required field "User.onboarding_state"`)}
	}
	if _, ok := _c.mutation.OnboardingCompleted(); !ok {
		return &ValidationError{Name: "onboarding_completed", err: errors.New(`ent: missing required field "User.onboarding_completed"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TelegramID(); ok {
		_spec.SetField(user.FieldTelegramID, field.TypeInt64, value)
		_node.TelegramID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(user.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(user.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.IsPremium(); ok {
		_spec.SetField(user.FieldIsPremium, field.TypeBool, value)
		_node.IsPremium = value
	}
	if value, ok := _c.mutation.CurrentStreak(); ok {
		_spec.SetField(user.FieldCurrentStreak, field.TypeInt, value)
		_node.CurrentStreak = value
	}
	if value, ok := _c.mutation.ReferrerID(); ok {
		_spec.SetField(user.FieldReferrerID, field.TypeInt64, value)
		_node.ReferrerID = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.PhoneNumber(); ok {
		_spec.SetField(user.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = value
	}
	if value, ok := _c.mutation.OnboardingState(); ok {
		_spec.SetField(user.FieldOnboardingState, field.TypeString, value)
		_node.OnboardingState = value
	}
	if value, ok := _c.mutation.OnboardingCompleted(); ok {
		_spec.SetField(user.FieldOnboardingCompleted, field.TypeBool, value)
		_node.OnboardingCompleted = value
	}
	if value, ok := _c.mutation.LastLogDate(); ok {
		_spec.SetField(user.FieldLastLogDate, field.TypeTime, value)
		_node.LastLogDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
