// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pocka/ent/budget"
	"pocka/ent/predicate"
	"pocka/ent/transaction"
	"pocka/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTelegramID sets the "telegram_id" field.
func (_u *UserUpdate) SetTelegramID(v int64) *UserUpdate {
	_u.mutation.ResetTelegramID()
	_u.mutation.SetTelegramID(v)
	return _u
}

// SetNillableTelegramID sets the "telegram_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTelegramID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetTelegramID(*v)
	}
	return _u
}

// AddTelegramID adds value to the "telegram_id" field.
func (_u *UserUpdate) AddTelegramID(v int64) *UserUpdate {
	_u.mutation.AddTelegramID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdate) ClearUsername() *UserUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserUpdate) SetTimezone(v string) *UserUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTimezone(v *string) *UserUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *UserUpdate) SetCurrency(v string) *UserUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCurrency(v *string) *UserUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *UserUpdate) SetLanguage(v string) *UserUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLanguage(v *string) *UserUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetIsPremium sets the "is_premium" field.
func (_u *UserUpdate) SetIsPremium(v bool) *UserUpdate {
	_u.mutation.SetIsPremium(v)
	return _u
}

// SetNillableIsPremium sets the "is_premium" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsPremium(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsPremium(*v)
	}
	return _u
}

// SetCurrentStreak sets the "current_streak" field.
func (_u *UserUpdate) SetCurrentStreak(v int) *UserUpdate {
	_u.mutation.ResetCurrentStreak()
	_u.mutation.SetCurrentStreak(v)
	return _u
}

// SetNillableCurrentStreak sets the "current_streak" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCurrentStreak(v *int) *UserUpdate {
	if v != nil {
		_u.SetCurrentStreak(*v)
	}
	return _u
}

// AddCurrentStreak adds value to the "current_streak" field.
func (_u *UserUpdate) AddCurrentStreak(v int) *UserUpdate {
	_u.mutation.AddCurrentStreak(v)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *UserUpdate) SetReferrerID(v int64) *UserUpdate {
	_u.mutation.ResetReferrerID()
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableReferrerID(v *int64) *UserUpdate {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// AddReferrerID adds value to the "referrer_id" field.
func (_u *UserUpdate) AddReferrerID(v int64) *UserUpdate {
	_u.mutation.AddReferrerID(v)
	return _u
}

// ClearReferrerID clears the value of the "referrer_id" field.
func (_u *UserUpdate) ClearReferrerID() *UserUpdate {
	_u.mutation.ClearReferrerID()
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserUpdate) SetFullName(v string) *UserUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableFullName(v *string) *UserUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// ClearFullName clears the value of the "full_name" field.
func (_u *UserUpdate) ClearFullName() *UserUpdate {
	_u.mutation.ClearFullName()
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *UserUpdate) SetPhoneNumber(v string) *UserUpdate {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhoneNumber(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *UserUpdate) ClearPhoneNumber() *UserUpdate {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetOnboardingState sets the "onboarding_state" field.
func (_u *UserUpdate) SetOnboardingState(v string) *UserUpdate {
	_u.mutation.SetOnboardingState(v)
	return _u
}

// SetNillableOnboardingState sets the "onboarding_state" field if the given value is not nil.
func (_u *UserUpdate) SetNillableOnboardingState(v *string) *UserUpdate {
	if v != nil {
		_u.SetOnboardingState(*v)
	}
	return _u
}

// SetOnboardingCompleted sets the "onboarding_completed" field.
func (_u *UserUpdate) SetOnboardingCompleted(v bool) *UserUpdate {
	_u.mutation.SetOnboardingCompleted(v)
	return _u
}

// SetNillableOnboardingCompleted sets the "onboarding_completed" field if the given value is not nil.
func (_u *UserUpdate) SetNillableOnboardingCompleted(v *bool) *UserUpdate {
	if v != nil {
		_u.SetOnboardingCompleted(*v)
	}
	return _u
}

// SetLastLogDate sets the "last_log_date" field.
func (_u *UserUpdate) SetLastLogDate(v time.Time) *UserUpdate {
	_u.mutation.SetLastLogDate(v)
	return _u
}

// SetNillableLastLogDate sets the "last_log_date" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLogDate(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLogDate(*v)
	}
	return _u
}

// ClearLastLogDate clears the value of the "last_log_date" field.
func (_u *UserUpdate) ClearLastLogDate() *UserUpdate {
	_u.mutation.ClearLastLogDate()
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *UserUpdate) AddTransactionIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *UserUpdate) AddTransactions(v ...*Transaction) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (_u *UserUpdate) AddBudgetIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddBudgetIDs(ids...)
	return _u
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (_u *UserUpdate) AddBudgets(v ...*Budget) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *UserUpdate) ClearTransactions() *UserUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *UserUpdate) RemoveTransactionIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *UserUpdate) RemoveTransactions(v ...*Transaction) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearBudgets clears all "budgets" edges to the Budget entity.
func (_u *UserUpdate) ClearBudgets() *UserUpdate {
	_u.mutation.ClearBudgets()
	return _u
}

// RemoveBudgetIDs removes the "budgets" edge to Budget entities by IDs.
func (_u *UserUpdate) RemoveBudgetIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveBudgetIDs(ids...)
	return _u
}

// RemoveBudgets removes "budgets" edges to Budget entities.
func (_u *UserUpdate) RemoveBudgets(v ...*Budget) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramID(); ok {
		_spec.SetField(user.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramID(); ok {
		_spec.AddField(user.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(user.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(user.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPremium(); ok {
		_spec.SetField(user.FieldIsPremium, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentStreak(); ok {
		_spec.SetField(user.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStreak(); ok {
		_spec.AddField(user.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReferrerID(); ok {
		_spec.SetField(user.FieldReferrerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferrerID(); ok {
		_spec.AddField(user.FieldReferrerID, field.TypeInt64, value)
	}
	if _u.mutation.ReferrerIDCleared() {
		_spec.ClearField(user.FieldReferrerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(user.FieldFullName, field.TypeString)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(user.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(user.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.OnboardingState(); ok {
		_spec.SetField(user.FieldOnboardingState, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnboardingCompleted(); ok {
		_spec.SetField(user.FieldOnboardingCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogDate(); ok {
		_spec.SetField(user.FieldLastLogDate, field.TypeTime, value)
	}
	if _u.mutation.LastLogDateCleared() {
		_spec.ClearField(user.FieldLastLogDate, field.TypeTime)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetsIDs(); len(nodes) > 0 && !_u.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetTelegramID sets the "telegram_id" field.
func (_u *UserUpdateOne) SetTelegramID(v int64) *UserUpdateOne {
	_u.mutation.ResetTelegramID()
	_u.mutation.SetTelegramID(v)
	return _u
}

// SetNillableTelegramID sets the "telegram_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTelegramID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetTelegramID(*v)
	}
	return _u
}

// AddTelegramID adds value to the "telegram_id" field.
func (_u *UserUpdateOne) AddTelegramID(v int64) *UserUpdateOne {
	_u.mutation.AddTelegramID(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdateOne) ClearUsername() *UserUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *UserUpdateOne) SetTimezone(v string) *UserUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTimezone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *UserUpdateOne) SetCurrency(v string) *UserUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCurrency(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *UserUpdateOne) SetLanguage(v string) *UserUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLanguage(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetIsPremium sets the "is_premium" field.
func (_u *UserUpdateOne) SetIsPremium(v bool) *UserUpdateOne {
	_u.mutation.SetIsPremium(v)
	return _u
}

// SetNillableIsPremium sets the "is_premium" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsPremium(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsPremium(*v)
	}
	return _u
}

// SetCurrentStreak sets the "current_streak" field.
func (_u *UserUpdateOne) SetCurrentStreak(v int) *UserUpdateOne {
	_u.mutation.ResetCurrentStreak()
	_u.mutation.SetCurrentStreak(v)
	return _u
}

// SetNillableCurrentStreak sets the "current_streak" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCurrentStreak(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetCurrentStreak(*v)
	}
	return _u
}

// AddCurrentStreak adds value to the "current_streak" field.
func (_u *UserUpdateOne) AddCurrentStreak(v int) *UserUpdateOne {
	_u.mutation.AddCurrentStreak(v)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *UserUpdateOne) SetReferrerID(v int64) *UserUpdateOne {
	_u.mutation.ResetReferrerID()
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableReferrerID(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// AddReferrerID adds value to the "referrer_id" field.
func (_u *UserUpdateOne) AddReferrerID(v int64) *UserUpdateOne {
	_u.mutation.AddReferrerID(v)
	return _u
}

// ClearReferrerID clears the value of the "referrer_id" field.
func (_u *UserUpdateOne) ClearReferrerID() *UserUpdateOne {
	_u.mutation.ClearReferrerID()
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UserUpdateOne) SetFullName(v string) *UserUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableFullName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// ClearFullName clears the value of the "full_name" field.
func (_u *UserUpdateOne) ClearFullName() *UserUpdateOne {
	_u.mutation.ClearFullName()
	return _u
}

// SetPhoneNumber sets the "phone_number" field.
func (_u *UserUpdateOne) SetPhoneNumber(v string) *UserUpdateOne {
	_u.mutation.SetPhoneNumber(v)
	return _u
}

// SetNillablePhoneNumber sets the "phone_number" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhoneNumber(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhoneNumber(*v)
	}
	return _u
}

// ClearPhoneNumber clears the value of the "phone_number" field.
func (_u *UserUpdateOne) ClearPhoneNumber() *UserUpdateOne {
	_u.mutation.ClearPhoneNumber()
	return _u
}

// SetOnboardingState sets the "onboarding_state" field.
func (_u *UserUpdateOne) SetOnboardingState(v string) *UserUpdateOne {
	_u.mutation.SetOnboardingState(v)
	return _u
}

// SetNillableOnboardingState sets the "onboarding_state" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableOnboardingState(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetOnboardingState(*v)
	}
	return _u
}

// SetOnboardingCompleted sets the "onboarding_completed" field.
func (_u *UserUpdateOne) SetOnboardingCompleted(v bool) *UserUpdateOne {
	_u.mutation.SetOnboardingCompleted(v)
	return _u
}

// SetNillableOnboardingCompleted sets the "onboarding_completed" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableOnboardingCompleted(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetOnboardingCompleted(*v)
	}
	return _u
}

// SetLastLogDate sets the "last_log_date" field.
func (_u *UserUpdateOne) SetLastLogDate(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLogDate(v)
	return _u
}

// SetNillableLastLogDate sets the "last_log_date" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLogDate(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLogDate(*v)
	}
	return _u
}

// ClearLastLogDate clears the value of the "last_log_date" field.
func (_u *UserUpdateOne) ClearLastLogDate() *UserUpdateOne {
	_u.mutation.ClearLastLogDate()
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *UserUpdateOne) AddTransactionIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *UserUpdateOne) AddTransactions(v ...*Transaction) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (_u *UserUpdateOne) AddBudgetIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddBudgetIDs(ids...)
	return _u
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (_u *UserUpdateOne) AddBudgets(v ...*Budget) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *UserUpdateOne) ClearTransactions() *UserUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *UserUpdateOne) RemoveTransactionIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *UserUpdateOne) RemoveTransactions(v ...*Transaction) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearBudgets clears all "budgets" edges to the Budget entity.
func (_u *UserUpdateOne) ClearBudgets() *UserUpdateOne {
	_u.mutation.ClearBudgets()
	return _u
}

// RemoveBudgetIDs removes the "budgets" edge to Budget entities by IDs.
func (_u *UserUpdateOne) RemoveBudgetIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveBudgetIDs(ids...)
	return _u
}

// RemoveBudgets removes "budgets" edges to Budget entities.
func (_u *UserUpdateOne) RemoveBudgets(v ...*Budget) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramID(); ok {
		_spec.SetField(user.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramID(); ok {
		_spec.AddField(user.FieldTelegramID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(user.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(user.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPremium(); ok {
		_spec.SetField(user.FieldIsPremium, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentStreak(); ok {
		_spec.SetField(user.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStreak(); ok {
		_spec.AddField(user.FieldCurrentStreak, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReferrerID(); ok {
		_spec.SetField(user.FieldReferrerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferrerID(); ok {
		_spec.AddField(user.FieldReferrerID, field.TypeInt64, value)
	}
	if _u.mutation.ReferrerIDCleared() {
		_spec.ClearField(user.FieldReferrerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(user.FieldFullName, field.TypeString, value)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(user.FieldFullName, field.TypeString)
	}
	if value, ok := _u.mutation.PhoneNumber(); ok {
		_spec.SetField(user.FieldPhoneNumber, field.TypeString, value)
	}
	if _u.mutation.PhoneNumberCleared() {
		_spec.ClearField(user.FieldPhoneNumber, field.TypeString)
	}
	if value, ok := _u.mutation.OnboardingState(); ok {
		_spec.SetField(user.FieldOnboardingState, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnboardingCompleted(); ok {
		_spec.SetField(user.FieldOnboardingCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLogDate(); ok {
		_spec.SetField(user.FieldLastLogDate, field.TypeTime, value)
	}
	if _u.mutation.LastLogDateCleared() {
		_spec.ClearField(user.FieldLastLogDate, field.TypeTime)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionsTable,
			Columns: []string{user.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetsIDs(); len(nodes) > 0 && !_u.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
