// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTelegramID holds the string denoting the telegram_id field in the database.
	FieldTelegramID = "telegram_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldIsPremium holds the string denoting the is_premium field in the database.
	FieldIsPremium = "is_premium"
	// FieldCurrentStreak holds the string denoting the current_streak field in the database.
	FieldCurrentStreak = "current_streak"
	// FieldReferredBy holds the string denoting the referred_by field in the database.
	FieldReferredBy = "referred_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeExpenses holds the string denoting the expenses edge name in mutations.
	EdgeExpenses = "expenses"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ExpensesTable is the table that holds the expenses relation/edge.
	ExpensesTable = "expenses"
	// ExpensesInverseTable is the table name for the Expense entity.
	// It exists in this package in order to avoid circular dependency with the "expense" package.
	ExpensesInverseTable = "expenses"
	// ExpensesColumn is the table column denoting the expenses relation/edge.
	ExpensesColumn = "user_expenses"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldTelegramID,
	FieldUsername,
	FieldTimezone,
	FieldCurrency,
	FieldLanguage,
	FieldIsPremium,
	FieldCurrentStreak,
	FieldReferredBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimezone holds the default value on creation for the "timezone" field.
	DefaultTimezone string
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultIsPremium holds the default value on creation for the "is_premium" field.
	DefaultIsPremium bool
	// DefaultCurrentStreak holds the default value on creation for the "current_streak" field.
	DefaultCurrentStreak int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTelegramID orders the results by the telegram_id field.
func ByTelegramID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByIsPremium orders the results by the is_premium field.
func ByIsPremium(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPremium, opts...).ToFunc()
}

// ByCurrentStreak orders the results by the current_streak field.
func ByCurrentStreak(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStreak, opts...).ToFunc()
}

// ByReferredBy orders the results by the referred_by field.
func ByReferredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferredBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpensesCount orders the results by expenses count.
func ByExpensesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExpensesStep(), opts...)
	}
}

// ByExpenses orders the results by expenses terms.
func ByExpenses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExpensesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExpensesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExpensesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExpensesTable, ExpensesColumn),
	)
}
